name: mavlink2rest
description: mavlink2rest dart package app for mavlink2rest (rust language communication), you support Flutter Apps
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
